// Color-name / channel-name intl catalog, ported verbatim from
// @react-stately/color's intl/color/*.json (34 locales). Keep in sync
// with the vendored react-spectrum source on every pin bump.

export type ColorStringKey =
  | "hue"
  | "saturation"
  | "lightness"
  | "brightness"
  | "red"
  | "green"
  | "blue"
  | "alpha"
  | "colorName"
  | "transparentColorName"
  | "very dark"
  | "dark"
  | "light"
  | "very light"
  | "pale"
  | "grayish"
  | "vibrant"
  | "black"
  | "white"
  | "gray"
  | "pink"
  | "pink red"
  | "red orange"
  | "brown"
  | "orange"
  | "orange yellow"
  | "brown yellow"
  | "yellow"
  | "yellow green"
  | "green cyan"
  | "cyan"
  | "cyan blue"
  | "blue purple"
  | "purple"
  | "purple magenta"
  | "magenta"
  | "magenta pink";

export const colorStrings: Record<string, Record<ColorStringKey, string>> = {
  "en-US": {
    "hue": "Hue",
    "saturation": "Saturation",
    "lightness": "Lightness",
    "brightness": "Brightness",
    "red": "Red",
    "green": "Green",
    "blue": "Blue",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparent",
    "very dark": "very dark",
    "dark": "dark",
    "light": "light",
    "very light": "very light",
    "pale": "pale",
    "grayish": "grayish",
    "vibrant": "vibrant",
    "black": "black",
    "white": "white",
    "gray": "gray",
    "pink": "pink",
    "pink red": "pink red",
    "red orange": "red orange",
    "brown": "brown",
    "orange": "orange",
    "orange yellow": "orange yellow",
    "brown yellow": "brown yellow",
    "yellow": "yellow",
    "yellow green": "yellow green",
    "green cyan": "green cyan",
    "cyan": "cyan",
    "cyan blue": "cyan blue",
    "blue purple": "blue purple",
    "purple": "purple",
    "purple magenta": "purple magenta",
    "magenta": "magenta",
    "magenta pink": "magenta pink",
  },
  "ar-AE": {
    "hue": "درجة اللون",
    "saturation": "التشبع",
    "lightness": "الإضاءة",
    "brightness": "السطوع",
    "red": "أحمر",
    "green": "أخضر",
    "blue": "أزرق",
    "alpha": "ألفا",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} شفاف",
    "very dark": "داكن جدًا",
    "dark": "داكن",
    "light": "فاتح",
    "very light": "فاتح جدًا",
    "pale": "باهت",
    "grayish": "مائل للرمادي",
    "vibrant": "ساطع",
    "black": "أسود",
    "white": "أبيض",
    "gray": "رمادي",
    "pink": "وردي",
    "pink red": "أحمر وردي",
    "red orange": "برتقالي محمر",
    "brown": "بني",
    "orange": "برتقالي",
    "orange yellow": "أصفر برتقالي",
    "brown yellow": "أصفر بني",
    "yellow": "أصفر",
    "yellow green": "أخضر مصفر",
    "green cyan": "سماوي مخضر",
    "cyan": "سماوي",
    "cyan blue": "أزرق سماوي",
    "blue purple": "أرجواني مزرق",
    "purple": "أرجواني",
    "purple magenta": "بنفسجي",
    "magenta": "أرجواني",
    "magenta pink": "أرجواني وردي",
  },
  "bg-BG": {
    "hue": "Оттенък",
    "saturation": "Наситеност",
    "lightness": "Лекота",
    "brightness": "Яркост",
    "red": "Червено",
    "green": "Зелено",
    "blue": "Синьо",
    "alpha": "Алфа",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} прозрачен",
    "very dark": "много тъмно",
    "dark": "тъмно",
    "light": "светло",
    "very light": "много светло",
    "pale": "бледо",
    "grayish": "сивкав",
    "vibrant": " ярко",
    "black": "черно",
    "white": "бяло",
    "gray": "сиво",
    "pink": "розово",
    "pink red": "розово червено",
    "red orange": "червен портокал",
    "brown": "кафяво",
    "orange": "оранжево",
    "orange yellow": "оранжево жълто",
    "brown yellow": "кафяво жълто",
    "yellow": "жълто",
    "yellow green": "жълто зелен",
    "green cyan": "зелен циан",
    "cyan": "циан",
    "cyan blue": "циан синьо",
    "blue purple": "синьо лилаво",
    "purple": "лилаво",
    "purple magenta": "лилаво магента",
    "magenta": "магента",
    "magenta pink": "магента розово",
  },
  "cs-CZ": {
    "hue": "Odstín",
    "saturation": "Sytost",
    "lightness": "Světlost",
    "brightness": "Jas",
    "red": "Červená",
    "green": "Zelená",
    "blue": "Modrá",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} průhledné",
    "very dark": "velmi tmavá",
    "dark": "tmavá",
    "light": "světlá",
    "very light": "velmi světlá",
    "pale": "bledá",
    "grayish": "našedlá",
    "vibrant": "zářivá",
    "black": "černá",
    "white": "bílá",
    "gray": "šedá",
    "pink": "růžová",
    "pink red": "růžovočervená",
    "red orange": "červenooranžová",
    "brown": "hnědá",
    "orange": "oranžová",
    "orange yellow": "oranžovožlutá",
    "brown yellow": "hnědožlutá",
    "yellow": "žlutá",
    "yellow green": "žlutozelená",
    "green cyan": "zelenotyrkysová",
    "cyan": "tyrkysová",
    "cyan blue": "tyrkysovomodrá",
    "blue purple": "modrofialová",
    "purple": "fialová",
    "purple magenta": "fialově purpurová",
    "magenta": "purpurová",
    "magenta pink": "purpurově růžová",
  },
  "da-DK": {
    "hue": "Tone",
    "saturation": "Farvemætning",
    "lightness": "Lyshed",
    "brightness": "Lysstyrke",
    "red": "Rød",
    "green": "Grøn",
    "blue": "Blå",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} gennemsigtig",
    "very dark": "meget mørk",
    "dark": "mørk",
    "light": "lys",
    "very light": "meget lys",
    "pale": "bleg",
    "grayish": "grålig",
    "vibrant": "klar",
    "black": "sort",
    "white": "hvid",
    "gray": "grå",
    "pink": "lyserød",
    "pink red": "lyserødlig rød",
    "red orange": "rødorange",
    "brown": "brun",
    "orange": "orange",
    "orange yellow": "orangegul",
    "brown yellow": "brungul",
    "yellow": "gul",
    "yellow green": "gulgrøn",
    "green cyan": "grøn cyan",
    "cyan": "cyan",
    "cyan blue": "cyan blå",
    "blue purple": "blålilla",
    "purple": "lilla",
    "purple magenta": "lilla magenta",
    "magenta": "magenta",
    "magenta pink": "magenta pink",
  },
  "de-DE": {
    "hue": "Farbton",
    "saturation": "Sättigung",
    "lightness": "Leuchtkraft",
    "brightness": "Helligkeit",
    "red": "Rot",
    "green": "Grün",
    "blue": "Blau",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, zu {percentTransparent} transparent",
    "very dark": "sehr dunkles",
    "dark": "dunkles",
    "light": "helles",
    "very light": "sehr helles",
    "pale": "blasses",
    "grayish": "gräuliches",
    "vibrant": "lebhaftes",
    "black": "Schwarz",
    "white": "Weiß",
    "gray": "Grau",
    "pink": "Rosa",
    "pink red": "Rosarot",
    "red orange": "Rotorange",
    "brown": "Braun",
    "orange": "Orange",
    "orange yellow": "Orangegelb",
    "brown yellow": "Braungelb",
    "yellow": "Gelb",
    "yellow green": "Gelbgrün",
    "green cyan": "Grüncyan",
    "cyan": "Cyan",
    "cyan blue": "Cyanblau",
    "blue purple": "Blaulila",
    "purple": "Lila",
    "purple magenta": "Lilamagenta",
    "magenta": "Magenta",
    "magenta pink": "Magentarosa",
  },
  "el-GR": {
    "hue": "Τόνος",
    "saturation": "Κορεσμός",
    "lightness": "Φωτεινότητα",
    "brightness": "Φωτεινότητα",
    "red": "Κόκκινο",
    "green": "Πράσινο",
    "blue": "Μπλε",
    "alpha": "Άλφα",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} διαφανές",
    "very dark": "πολύ σκούρο",
    "dark": "σκούρο",
    "light": "ανοιχτό",
    "very light": "πολύ ανοιχτό",
    "pale": "ανοιχτό",
    "grayish": "γκριζωπό",
    "vibrant": "έντονο",
    "black": "μαύρο",
    "white": "λευκό",
    "gray": "γκρι",
    "pink": "ροζ",
    "pink red": "ροζ κόκκινο",
    "red orange": "κόκκινο πορτοκαλί",
    "brown": "καφέ",
    "orange": "πορτοκαλί",
    "orange yellow": "πορτοκαλί κίτρινο",
    "brown yellow": "καφέ κίτρινο",
    "yellow": "κίτρινο",
    "yellow green": "κίτρινο πράσινο",
    "green cyan": "πράσινο κυανό",
    "cyan": "κυανό",
    "cyan blue": "κυανό μπλε",
    "blue purple": "μπλε μωβ",
    "purple": "μωβ",
    "purple magenta": "μωβ ματζέντα",
    "magenta": "ματζέντα",
    "magenta pink": "ματζέντα ροζ",
  },
  "es-ES": {
    "hue": "Tono",
    "saturation": "Saturación",
    "lightness": "Luminosidad",
    "brightness": "Brillo",
    "red": "Rojo",
    "green": "Verde",
    "blue": "Azul",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparente",
    "very dark": "muy oscuro",
    "dark": "oscuro",
    "light": "claro",
    "very light": "muy claro",
    "pale": "pálido",
    "grayish": "grisáceo",
    "vibrant": "intenso",
    "black": "negro",
    "white": "blanco",
    "gray": "gris",
    "pink": "rosa",
    "pink red": "rojo rosado",
    "red orange": "naranja rojizo",
    "brown": "marrón",
    "orange": "naranja",
    "orange yellow": "amarillo anaranjado",
    "brown yellow": "amarillo amarronado",
    "yellow": "amarillo",
    "yellow green": "verde amarillento",
    "green cyan": "cian verdoso",
    "cyan": "cian",
    "cyan blue": "azul cian",
    "blue purple": "púrpura azulado",
    "purple": "morado",
    "purple magenta": "magenta violáceo",
    "magenta": "magenta",
    "magenta pink": "rosa magenta",
  },
  "et-EE": {
    "hue": "Värv",
    "saturation": "Küllastus",
    "lightness": "Valgus",
    "brightness": "Heledus",
    "red": "Punane",
    "green": "Roheline",
    "blue": "Sinine",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} läbipaistev",
    "very dark": "väga tume",
    "dark": "tume",
    "light": "valgus",
    "very light": "väga hele",
    "pale": "kahvatu",
    "grayish": "hallikas",
    "vibrant": "ere",
    "black": "must",
    "white": "valge",
    "gray": "hall",
    "pink": "roosa",
    "pink red": "vaarikapunane",
    "red orange": "punakasoranž",
    "brown": "pruun",
    "orange": "oranž",
    "orange yellow": "oranžikaskollane",
    "brown yellow": "pruunikaskollane",
    "yellow": "kollane",
    "yellow green": "kollakasroheline",
    "green cyan": "tsüaanroheline",
    "cyan": "tsüaan",
    "cyan blue": "tsüaansinine",
    "blue purple": "sinakaslilla",
    "purple": "lilla",
    "purple magenta": "purpurne magenta",
    "magenta": "magentapunane",
    "magenta pink": "magentaroosa",
  },
  "fi-FI": {
    "hue": "Sävy",
    "saturation": "Värikylläisyys",
    "lightness": "Valomäärä",
    "brightness": "Kirkkaus",
    "red": "Punainen",
    "green": "Vihreä",
    "blue": "Sininen",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} läpinäkyvä",
    "very dark": "hyvin tumma",
    "dark": "tumma",
    "light": "vaalea",
    "very light": "erittäin vaalea",
    "pale": "vaalea",
    "grayish": "harmahtava",
    "vibrant": "eloisa",
    "black": "musta",
    "white": "valkea",
    "gray": "harmaa",
    "pink": "pinkki",
    "pink red": "vaaleanpunainen",
    "red orange": "punaoranssi",
    "brown": "ruskea",
    "orange": "oranssi",
    "orange yellow": "oranssinkeltainen",
    "brown yellow": "ruskeankeltainen",
    "yellow": "keltainen",
    "yellow green": "keltavihreä",
    "green cyan": "vihreänsyaani",
    "cyan": "syaani",
    "cyan blue": "syaaninsininen",
    "blue purple": "sinivioletti",
    "purple": "violetti",
    "purple magenta": "violettimagenta",
    "magenta": "magenta",
    "magenta pink": "magentapinkki",
  },
  "fr-FR": {
    "hue": "Teinte",
    "saturation": "Saturation",
    "lightness": "Luminosité",
    "brightness": "Luminosité",
    "red": "Rouge",
    "green": "Vert",
    "blue": "Bleu",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparent",
    "very dark": "Très sombre",
    "dark": "Sombre",
    "light": "Clair",
    "very light": "Très clair",
    "pale": "Pâle",
    "grayish": "Grisâtre",
    "vibrant": "Vif",
    "black": "Noir",
    "white": "Blanc",
    "gray": "Gris",
    "pink": "Rose",
    "pink red": "Rouge rosé",
    "red orange": "Orange rouge",
    "brown": "Brun",
    "orange": "Orange",
    "orange yellow": "Jaune orangé",
    "brown yellow": "Jaune brun",
    "yellow": "Jaune",
    "yellow green": "Vert jaune",
    "green cyan": "Cyan vert",
    "cyan": "Cyan",
    "cyan blue": "Bleu cyan",
    "blue purple": "Violet bleu",
    "purple": "Violet",
    "purple magenta": "Magenta violet",
    "magenta": "Magenta",
    "magenta pink": "Rose magenta",
  },
  "he-IL": {
    "hue": "גוון",
    "saturation": "רוויה",
    "lightness": "כמות אור",
    "brightness": "בהירות",
    "red": "אדום",
    "green": "ירוק",
    "blue": "כחול",
    "alpha": "אלפא",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} שקוף",
    "very dark": "כהה מאוד",
    "dark": "כהה",
    "light": "אור",
    "very light": "בהיר מאוד",
    "pale": "חיוור",
    "grayish": "אפרפר",
    "vibrant": "תוסס",
    "black": "שחור",
    "white": "לבן",
    "gray": "אפור",
    "pink": "ורוד",
    "pink red": "ורוד אדום",
    "red orange": "כתום אדום",
    "brown": "חום",
    "orange": "כתום",
    "orange yellow": "כתום צהוב",
    "brown yellow": "חום צהוב",
    "yellow": "צהוב",
    "yellow green": "צהוב ירוק",
    "green cyan": "ציאן ירוק",
    "cyan": "טורקיז",
    "cyan blue": "כחול ציאן",
    "blue purple": "כחול סגול",
    "purple": "סגול",
    "purple magenta": "מג'נטה סגול",
    "magenta": "מג'נטה",
    "magenta pink": "ורוד מג'נטה",
  },
  "hr-HR": {
    "hue": "Nijansa",
    "saturation": "Zasićenost",
    "lightness": "Osvijetljenost",
    "brightness": "Svjetlina",
    "red": "Crvena",
    "green": "Zelena",
    "blue": "Plava",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} prozirnosti",
    "very dark": "jako tamna",
    "dark": "tamno",
    "light": "svjetlo",
    "very light": "vrlo svijetlo",
    "pale": "blijeda",
    "grayish": "sivkasto",
    "vibrant": "vibrantna",
    "black": "crno",
    "white": "bijela",
    "gray": "siva",
    "pink": "ružičasta",
    "pink red": "ružičasto crvena",
    "red orange": "crveno narančasta",
    "brown": "smeđa",
    "orange": "narančasta",
    "orange yellow": "narančasto žuta",
    "brown yellow": "smeđe žuta",
    "yellow": "žuto",
    "yellow green": "žuto zelena",
    "green cyan": "zelena cijan",
    "cyan": "cijan",
    "cyan blue": "cijan plava",
    "blue purple": "plavo ljubičasta",
    "purple": "ljubičasta",
    "purple magenta": "ljubičasta magenta",
    "magenta": "magenta",
    "magenta pink": "magentno ružičasta",
  },
  "hu-HU": {
    "hue": "Színárnyalat",
    "saturation": "Telítettség",
    "lightness": "Világosság",
    "brightness": "Fényesség",
    "red": "Piros",
    "green": "Zöld",
    "blue": "Kék",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} átlátszó",
    "very dark": "nagyon sötét",
    "dark": "sötét",
    "light": "világos",
    "very light": "nagyon világos",
    "pale": "halvány",
    "grayish": "szürkés",
    "vibrant": "élénk",
    "black": "fekete",
    "white": "fehér",
    "gray": "szürke",
    "pink": "rózsaszín",
    "pink red": "rózsaszín piros",
    "red orange": "piros narancs",
    "brown": "barna",
    "orange": "narancs",
    "orange yellow": "narancssárga",
    "brown yellow": "barna sárga",
    "yellow": "sárga",
    "yellow green": "sárga zöld",
    "green cyan": "zöld ciánkék",
    "cyan": "ciánkék",
    "cyan blue": "ciánkék",
    "blue purple": "kék lila",
    "purple": "lila",
    "purple magenta": "lila bíbor",
    "magenta": "bíbor",
    "magenta pink": "bíbor rózsaszín",
  },
  "it-IT": {
    "hue": "Tonalità",
    "saturation": "Saturazione",
    "lightness": "Luminosità",
    "brightness": "Luminosità",
    "red": "Rosso",
    "green": "Verde",
    "blue": "Blu",
    "alpha": "Alfa",
    "colorName": "{hue} {chroma} {lightness}",
    "transparentColorName": "{hue} {chroma} {lightness}, trasparenza {percentTransparent}",
    "very dark": "molto scuro",
    "dark": "scuro",
    "light": "chiaro",
    "very light": "molto chiaro",
    "pale": "tenue",
    "grayish": "grigiastro",
    "vibrant": "vivace",
    "black": "nero",
    "white": "bianco",
    "gray": "grigio",
    "pink": "rosa",
    "pink red": "rosa rosso",
    "red orange": "rosso arancio",
    "brown": "marrone",
    "orange": "arancio",
    "orange yellow": "giallo arancio",
    "brown yellow": "giallo bruno",
    "yellow": "giallo",
    "yellow green": "giallo verde",
    "green cyan": "verde ciano",
    "cyan": "ciano",
    "cyan blue": "blu ciano",
    "blue purple": "blu viola",
    "purple": "viola",
    "purple magenta": "viola magenta",
    "magenta": "magenta",
    "magenta pink": "rosa magenta",
  },
  "ja-JP": {
    "hue": "色相",
    "saturation": "彩度",
    "lightness": "明度",
    "brightness": "明るさ",
    "red": "赤",
    "green": "緑",
    "blue": "青",
    "alpha": "アルファ",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} 透明",
    "very dark": "最も暗い",
    "dark": "ダーク",
    "light": "ライト",
    "very light": "ベリーライト",
    "pale": "ペール",
    "grayish": "グレイッシュ",
    "vibrant": "鮮やか",
    "black": "ブラック",
    "white": "ホワイト",
    "gray": "グレー",
    "pink": "ピンク",
    "pink red": "ピンクレッド",
    "red orange": "レッドオレンジ",
    "brown": "ブラウン",
    "orange": "オレンジ",
    "orange yellow": "オレンジイエロー",
    "brown yellow": "ブラウンイエロー",
    "yellow": "イエロー",
    "yellow green": "イエローグリーン",
    "green cyan": "グリーンシアン",
    "cyan": "シアン",
    "cyan blue": "シアンブルー",
    "blue purple": "ブルーパープル",
    "purple": "パープル",
    "purple magenta": "パープルマゼンタ",
    "magenta": "マゼンタ",
    "magenta pink": "マゼンタピンク",
  },
  "ko-KR": {
    "hue": "색조",
    "saturation": "채도",
    "lightness": "밝기",
    "brightness": "명도",
    "red": "빨강",
    "green": "초록",
    "blue": "파랑",
    "alpha": "알파",
    "colorName": "{lightness}, {chroma}, {hue}",
    "transparentColorName": "{lightness}, {chroma}, {hue}, {percentTransparent} 투명도",
    "very dark": "매우 어두운",
    "dark": "다크",
    "light": "라이트",
    "very light": "매우 연함",
    "pale": "흙색",
    "grayish": "회갈색",
    "vibrant": "강렬한",
    "black": "검은색",
    "white": "흰색",
    "gray": "회색",
    "pink": "분홍색",
    "pink red": "핑크 레드",
    "red orange": "붉은 주황색",
    "brown": "갈색",
    "orange": "주황색",
    "orange yellow": "불그스름한 노랑",
    "brown yellow": "황갈색",
    "yellow": "노란색",
    "yellow green": "연두색",
    "green cyan": "청록색",
    "cyan": "청록색",
    "cyan blue": "청록색",
    "blue purple": "청자색",
    "purple": "자주색",
    "purple magenta": "보라빛 자홍색",
    "magenta": "자홍색",
    "magenta pink": "마젠타 핑크",
  },
  "lt-LT": {
    "hue": "Atspalvis",
    "saturation": "Įsotinimas",
    "lightness": "Šviesumas",
    "brightness": "Ryškumas",
    "red": "Raudona",
    "green": "Žalia",
    "blue": "Mėlyna",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} skaidri",
    "very dark": "labai tamsi",
    "dark": "tamsi",
    "light": "šviesi",
    "very light": "labai šviesi",
    "pale": "blyški",
    "grayish": "pilkšva",
    "vibrant": "ryški",
    "black": "juoda",
    "white": "balta",
    "gray": "pilka",
    "pink": "rožinė",
    "pink red": "rožinė raudona",
    "red orange": "rausvai oranžinė",
    "brown": "ruda",
    "orange": "oranžinė",
    "orange yellow": "oranžinio atspalvio geltona",
    "brown yellow": "rusvai geltona",
    "yellow": "geltona",
    "yellow green": "gelsvai žalia",
    "green cyan": "žalsvai mėlyna",
    "cyan": "žalsvai mėlyna",
    "cyan blue": "žalsvai mėlyna",
    "blue purple": "melsvai violetinė",
    "purple": "violetinė",
    "purple magenta": "purpurinė rausvai raudona",
    "magenta": "rausvai raudona",
    "magenta pink": "purpurinė",
  },
  "lv-LV": {
    "hue": "Nokrāsa",
    "saturation": "Piesātinājums",
    "lightness": "Gaišums",
    "brightness": "Spilgtums",
    "red": "Sarkana",
    "green": "Zaļa",
    "blue": "Zila",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} caurspīdīgs",
    "very dark": "ļoti tumšs",
    "dark": "tumšs",
    "light": "gaišs",
    "very light": "ļoti gaišs",
    "pale": "bāls",
    "grayish": "pelēcīgs",
    "vibrant": "košs",
    "black": "melns",
    "white": "balts",
    "gray": "pelēks",
    "pink": "rozā",
    "pink red": "rozīgi sarkans",
    "red orange": "sarkanīgi oranžs",
    "brown": "brūns",
    "orange": "oranžs",
    "orange yellow": "oranži dzeltens",
    "brown yellow": "brūni dzeltens",
    "yellow": "dzeltens",
    "yellow green": "dzelteni zaļš",
    "green cyan": "zaļš ciāns",
    "cyan": "ciāns",
    "cyan blue": "ciāna zils",
    "blue purple": "zili violets",
    "purple": "violets",
    "purple magenta": "violets fuksiju",
    "magenta": "fuksiju",
    "magenta pink": "fuksiju rozā",
  },
  "nb-NO": {
    "hue": "Fargetone",
    "saturation": "Metning",
    "lightness": "Lyshet",
    "brightness": "Lysstyrke",
    "red": "Rød",
    "green": "Grønn",
    "blue": "Blå",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} gjennomsiktig",
    "very dark": "svært mørk",
    "dark": "mørk",
    "light": "lys",
    "very light": "svært lys",
    "pale": "blek",
    "grayish": "gråaktig",
    "vibrant": "levende",
    "black": "svart",
    "white": "hvit",
    "gray": "grå",
    "pink": "rosa",
    "pink red": "rosarød",
    "red orange": "rødoransje",
    "brown": "brun",
    "orange": "oransje",
    "orange yellow": "oransjegul",
    "brown yellow": "brungul",
    "yellow": "gul",
    "yellow green": "gulgrønn",
    "green cyan": "grønncyan",
    "cyan": "cyan",
    "cyan blue": "cyanblå",
    "blue purple": "blålilla",
    "purple": "lilla",
    "purple magenta": "lillamagenta",
    "magenta": "magenta",
    "magenta pink": "magentarosa",
  },
  "nl-NL": {
    "hue": "Kleurtoon",
    "saturation": "Verzadiging",
    "lightness": "Lichtsterkte",
    "brightness": "Helderheid",
    "red": "Rood",
    "green": "Groen",
    "blue": "Blauw",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparant",
    "very dark": "heel donker",
    "dark": "donker",
    "light": "licht",
    "very light": "heel licht",
    "pale": "bleek",
    "grayish": "grijsachtig",
    "vibrant": "levendig",
    "black": "zwart",
    "white": "wit",
    "gray": "grijs",
    "pink": "roze",
    "pink red": "rozerood",
    "red orange": "roodoranje",
    "brown": "bruin",
    "orange": "oranje",
    "orange yellow": "oranjegeel",
    "brown yellow": "bruingeel",
    "yellow": "geel",
    "yellow green": "geelgroen",
    "green cyan": "cyaangroen",
    "cyan": "cyaan",
    "cyan blue": "cyaanblauw",
    "blue purple": "paarsblauw",
    "purple": "paars",
    "purple magenta": "magentapaars",
    "magenta": "magenta",
    "magenta pink": "magentaroze",
  },
  "pl-PL": {
    "hue": "Odcień",
    "saturation": "Nasycenie",
    "lightness": "Jaskrawość",
    "brightness": "Jasność",
    "red": "Czerwony",
    "green": "Zielony",
    "blue": "Niebieski",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} przezroczystości",
    "very dark": "bardzo ciemny",
    "dark": "ciemny",
    "light": "jasny",
    "very light": "bardzo jasny",
    "pale": "blady",
    "grayish": "szarawy",
    "vibrant": "intensywny",
    "black": "czarny",
    "white": "biały",
    "gray": "szary",
    "pink": "różowy",
    "pink red": "różowo-czerwony",
    "red orange": "czerwono-pomarańczowy",
    "brown": "brązowy",
    "orange": "pomarańczowy",
    "orange yellow": "pomarańczowo-żółty",
    "brown yellow": "brązowo-żółty",
    "yellow": "żółty",
    "yellow green": "żółto-zielony",
    "green cyan": "zielono-cyjanowy",
    "cyan": "cyjanowy",
    "cyan blue": "cyjanowo-niebieski",
    "blue purple": "niebiesko-fioletowy",
    "purple": "fioletowy",
    "purple magenta": "fioletowo-purpurowy",
    "magenta": "purpurowy",
    "magenta pink": "purpurowo-różowy",
  },
  "pt-BR": {
    "hue": "Matiz",
    "saturation": "Saturação",
    "lightness": "Luminosidade",
    "brightness": "Brilho",
    "red": "Vermelho",
    "green": "Verde",
    "blue": "Azul",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparente",
    "very dark": "muito escuro",
    "dark": "escuro",
    "light": "claro",
    "very light": "muito claro",
    "pale": "pálido",
    "grayish": "acinzentado",
    "vibrant": "vibrante",
    "black": "preto",
    "white": "branco",
    "gray": "cinza",
    "pink": "rosa",
    "pink red": "rosa avermelhado",
    "red orange": "laranja avermelhado",
    "brown": "marrom",
    "orange": "laranja",
    "orange yellow": "amarelo alaranjado",
    "brown yellow": "marrom amarelado",
    "yellow": "amarelo",
    "yellow green": "verde amarelado",
    "green cyan": "verde-ciano",
    "cyan": "ciano",
    "cyan blue": "azul-ciano",
    "blue purple": "roxo azulado",
    "purple": "roxo",
    "purple magenta": "roxo-magenta",
    "magenta": "magenta",
    "magenta pink": "rosa-magenta",
  },
  "pt-PT": {
    "hue": "Tonalidade",
    "saturation": "Saturação",
    "lightness": "Claridade",
    "brightness": "Luminosidade",
    "red": "Vermelho",
    "green": "Verde",
    "blue": "Azul",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparente",
    "very dark": "muito escuro",
    "dark": "escuro",
    "light": "claro",
    "very light": "muito claro",
    "pale": "pálido",
    "grayish": "acinzentado",
    "vibrant": "vibrante",
    "black": "preto",
    "white": "branco",
    "gray": "cinzento",
    "pink": "cor-de-rosa",
    "pink red": "vermelho-rosa",
    "red orange": "laranja-vermelho",
    "brown": "castanho",
    "orange": "laranja",
    "orange yellow": "amarelo-laranja",
    "brown yellow": "amarelo-castanho",
    "yellow": "amarelo",
    "yellow green": "verde-amarelo",
    "green cyan": "verde-ciano",
    "cyan": "ciano",
    "cyan blue": "azul-ciano",
    "blue purple": "azul-púrpura",
    "purple": "púrpura",
    "purple magenta": "púrpura-magenta",
    "magenta": "magenta",
    "magenta pink": "rosa-magenta",
  },
  "ro-RO": {
    "hue": "Nuanță",
    "saturation": "Saturație",
    "lightness": "Luminozitate",
    "brightness": "Luminozitate",
    "red": "Roșu",
    "green": "Verde",
    "blue": "Albastru",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} transparent",
    "very dark": "foarte închis",
    "dark": "închis",
    "light": "deschis",
    "very light": "foarte deschis",
    "pale": "pal",
    "grayish": "cenușiu",
    "vibrant": "plin de viață",
    "black": "negru",
    "white": "alb",
    "gray": "gri",
    "pink": "roz",
    "pink red": "roz-roșu",
    "red orange": "portocaliu-roșu",
    "brown": "maro",
    "orange": "portocaliu",
    "orange yellow": "galben-portocaliu",
    "brown yellow": "galben maro",
    "yellow": "galben",
    "yellow green": "galben-verde",
    "green cyan": "verde bleu",
    "cyan": "bleu",
    "cyan blue": "albastru-bleu",
    "blue purple": "albastru-violet",
    "purple": "violet",
    "purple magenta": "violet-fucsia",
    "magenta": "fucsia",
    "magenta pink": "roz-fucsia",
  },
  "ru-RU": {
    "hue": "Оттенок",
    "saturation": "Насыщенность",
    "lightness": "Освещенность",
    "brightness": "Яркость",
    "red": "Красный",
    "green": "Зеленый",
    "blue": "Синий",
    "alpha": "Альфа",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, прозрачный на {percentTransparent}",
    "very dark": "очень темный",
    "dark": "темный",
    "light": "светлый",
    "very light": "очень светлый",
    "pale": "бледный",
    "grayish": "сероватый",
    "vibrant": "яркий",
    "black": "черный",
    "white": "белый",
    "gray": "серый",
    "pink": "розовый",
    "pink red": "розово-красный",
    "red orange": "красно-оранжевый",
    "brown": "коричневый",
    "orange": "оранжевый",
    "orange yellow": "оранжево-желтый",
    "brown yellow": "коричнево-желтый",
    "yellow": "желтый",
    "yellow green": "желто-зеленый",
    "green cyan": "сине-зеленый",
    "cyan": "голубой",
    "cyan blue": "цвет морской волны",
    "blue purple": "сине-фиолетовый",
    "purple": "фиолетовый",
    "purple magenta": "фиолетово-пурпурный",
    "magenta": "пурпурный",
    "magenta pink": "пурпурно-розовый",
  },
  "sk-SK": {
    "hue": "Odtieň",
    "saturation": "Sýtosť",
    "lightness": "Svetlosť",
    "brightness": "Jas",
    "red": "Červená",
    "green": "Zelená",
    "blue": "Modrá",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} priehľadná",
    "very dark": "veľmi tmavá",
    "dark": "tmavá",
    "light": "svetlá",
    "very light": "veľmi svetlá",
    "pale": "bledá",
    "grayish": "sivastá",
    "vibrant": "energická",
    "black": "čierna",
    "white": "biela",
    "gray": "sivá",
    "pink": "ružová",
    "pink red": "ružovočervená",
    "red orange": "červenooranžová",
    "brown": "hnedá",
    "orange": "oranžová",
    "orange yellow": "oranžovožltá",
    "brown yellow": "hnedožltá",
    "yellow": "žltá",
    "yellow green": "žltozelená",
    "green cyan": "zelená azúrová",
    "cyan": "azúrová",
    "cyan blue": "azúrová modrá",
    "blue purple": "modrofialová",
    "purple": "fialová",
    "purple magenta": "fialová purpurová",
    "magenta": "purpurová",
    "magenta pink": "ružová purpurová",
  },
  "sl-SI": {
    "hue": "Barva",
    "saturation": "Nasičenost",
    "lightness": "Lahkost",
    "brightness": "Svetlost",
    "red": "Rdeča",
    "green": "Zelena",
    "blue": "Modra",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} prozorna",
    "very dark": "zelo temna",
    "dark": "temna",
    "light": "svetla",
    "very light": "zelo svetla",
    "pale": "bleda",
    "grayish": "sivkasta",
    "vibrant": "živahna",
    "black": "črna",
    "white": "bela",
    "gray": "siva",
    "pink": "roza",
    "pink red": "roza rdeča",
    "red orange": "rdeče oranžna",
    "brown": "rjava",
    "orange": "oranžna",
    "orange yellow": "oranžno rumena",
    "brown yellow": "rjavo rumena",
    "yellow": "rumena",
    "yellow green": "rumeno zelena",
    "green cyan": "zelena cian",
    "cyan": "cian",
    "cyan blue": "cian modra",
    "blue purple": "modro vijolična",
    "purple": "vijolična",
    "purple magenta": "vijolično škrlatna",
    "magenta": "škrlatna",
    "magenta pink": "škrlatno roza",
  },
  "sr-SP": {
    "hue": "Nijansa",
    "saturation": "Zasićenje",
    "lightness": "Osvetljenje",
    "brightness": "Osvetljenost",
    "red": "Crvena",
    "green": "Zelena",
    "blue": "Plava",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} prozirna",
    "very dark": "veoma tamno",
    "dark": "tamno",
    "light": "svetla",
    "very light": "vrlo svetlo",
    "pale": "bledo",
    "grayish": "sivkasta",
    "vibrant": "živopisna",
    "black": "crno",
    "white": "bela",
    "gray": "siva",
    "pink": "ružičasta",
    "pink red": "ružičastocrvena",
    "red orange": "crvenonarandžasta",
    "brown": "smeđa",
    "orange": "narandžasta",
    "orange yellow": "narandžastožuta",
    "brown yellow": "smeđežuta",
    "yellow": "žuto",
    "yellow green": "žutozelena",
    "green cyan": "zeleno cijan",
    "cyan": "cijan",
    "cyan blue": "cijan plava",
    "blue purple": "plavoljubičasta",
    "purple": "ljubičasta",
    "purple magenta": "ljubičasta magenta",
    "magenta": "purpurnocrvena",
    "magenta pink": "magenta ružičasta",
  },
  "sv-SE": {
    "hue": "Nyans",
    "saturation": "Mättnad",
    "lightness": "Ljushet",
    "brightness": "Ljusstyrka",
    "red": "Rött",
    "green": "Grönt",
    "blue": "Blått",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} genomskinlig",
    "very dark": "mycket mörk",
    "dark": "mörk",
    "light": "ljus",
    "very light": "mycket ljus",
    "pale": "blek",
    "grayish": "gråaktig",
    "vibrant": "livfull",
    "black": "svart",
    "white": "vit",
    "gray": "grå",
    "pink": "rosa",
    "pink red": "rosaröd",
    "red orange": "rödorange",
    "brown": "brun",
    "orange": "orange",
    "orange yellow": "orangegul",
    "brown yellow": "brungul",
    "yellow": "gul",
    "yellow green": "gulgrön",
    "green cyan": "grön cyan",
    "cyan": "cyan",
    "cyan blue": "cyanblå",
    "blue purple": "blålila",
    "purple": "lila",
    "purple magenta": "lila magenta",
    "magenta": "magenta",
    "magenta pink": "magentarosa",
  },
  "tr-TR": {
    "hue": "Ton",
    "saturation": "Doygunluk",
    "lightness": "Canlılık",
    "brightness": "Parlaklık",
    "red": "Kırmızı",
    "green": "Yeşil",
    "blue": "Mavi",
    "alpha": "Alfa",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} saydam",
    "very dark": "çok koyu",
    "dark": "koyu",
    "light": "açık",
    "very light": "çok açık",
    "pale": "solgun",
    "grayish": "grimsi",
    "vibrant": "canlı",
    "black": "siyah",
    "white": "beyaz",
    "gray": "gri",
    "pink": "pembe",
    "pink red": "pembe kırmızı",
    "red orange": "kırmızı portakal",
    "brown": "kahverengi",
    "orange": "turuncu",
    "orange yellow": "turuncu sarı",
    "brown yellow": "kahverengi sarı",
    "yellow": "sarı",
    "yellow green": "sarı yeşil",
    "green cyan": "yeşil camgöbeği",
    "cyan": "camgöbeği",
    "cyan blue": "camgöbeği mavi",
    "blue purple": "mavi mor",
    "purple": "mor",
    "purple magenta": "mor eflatun",
    "magenta": "eflatun",
    "magenta pink": "eflatun pembe",
  },
  "uk-UA": {
    "hue": "Тон",
    "saturation": "Насиченість",
    "lightness": "Освітленість",
    "brightness": "Яскравість",
    "red": "Червоний",
    "green": "Зелений",
    "blue": "Синій",
    "alpha": "Альфа",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, прозорий на {percentTransparent}",
    "very dark": "дуже темний",
    "dark": "темний",
    "light": "світлий",
    "very light": "дуже світлий",
    "pale": "блідий",
    "grayish": "сіруватий",
    "vibrant": "яскравий",
    "black": "чорний",
    "white": "білий",
    "gray": "сірий",
    "pink": "рожевий",
    "pink red": "рожево-червоний",
    "red orange": "червоно-помаранчевий",
    "brown": "коричневий",
    "orange": "помаранчевий",
    "orange yellow": "помаранчево-жовтий",
    "brown yellow": "коричнево-жовтий",
    "yellow": "жовтий",
    "yellow green": "жовто-зелений",
    "green cyan": "зелено-блакитний",
    "cyan": "блакитний",
    "cyan blue": "синьо-блакитний",
    "blue purple": "синьо-фіолетовий",
    "purple": "фіолетовий",
    "purple magenta": "фіолетово-пурпуровий",
    "magenta": "пурпуровий",
    "magenta pink": "пурпурово-рожевий",
  },
  "zh-CN": {
    "hue": "色相",
    "saturation": "饱和度",
    "lightness": "明亮度",
    "brightness": "亮度",
    "red": "红色",
    "green": "绿色",
    "blue": "蓝色",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} 透明",
    "very dark": "很暗",
    "dark": "深色",
    "light": "浅色",
    "very light": "很浅",
    "pale": "苍白的",
    "grayish": "浅灰色的",
    "vibrant": "生机勃勃",
    "black": "黑色",
    "white": "白色",
    "gray": "灰色",
    "pink": "粉色",
    "pink red": "粉红色",
    "red orange": "红橙色",
    "brown": "棕色的",
    "orange": "橙色",
    "orange yellow": "橙黄色",
    "brown yellow": "棕黄色",
    "yellow": "黄色",
    "yellow green": "黄色/绿色",
    "green cyan": "绿青色",
    "cyan": "蓝绿色",
    "cyan blue": "青蓝色",
    "blue purple": "蓝紫色",
    "purple": "紫色",
    "purple magenta": "紫洋红色",
    "magenta": "紫红色",
    "magenta pink": "紫粉色",
  },
  "zh-TW": {
    "hue": "色相",
    "saturation": "飽和度",
    "lightness": "明亮",
    "brightness": "亮度",
    "red": "紅色",
    "green": "綠色",
    "blue": "藍色",
    "alpha": "Alpha",
    "colorName": "{lightness} {chroma} {hue}",
    "transparentColorName": "{lightness} {chroma} {hue}, {percentTransparent} 透明",
    "very dark": "很暗",
    "dark": "暗",
    "light": "淺",
    "very light": "很淺",
    "pale": "淡",
    "grayish": "偏灰",
    "vibrant": "鮮豔",
    "black": "黑",
    "white": "白",
    "gray": "灰",
    "pink": "粉紅",
    "pink red": "粉紅",
    "red orange": "橙紅",
    "brown": "棕",
    "orange": "橙",
    "orange yellow": "橙黃",
    "brown yellow": "棕黃",
    "yellow": "黃",
    "yellow green": "黃綠",
    "green cyan": "青綠",
    "cyan": "青",
    "cyan blue": "青藍",
    "blue purple": "藍紫",
    "purple": "紫",
    "purple magenta": "紫洋紅",
    "magenta": "洋紅",
    "magenta pink": "淺洋紅",
  },
};

const DEFAULT_LOCALE = "en-US";

/**
 * Mirrors LocalizedStringDictionary.getStringForLocale: exact-locale match,
 * then language-only match (e.g. "ar" for "ar-AE"), then the en-US fallback.
 * Ported so solid-stately's Color needs no @internationalized/string dependency.
 */
export function getColorStringForLocale(key: ColorStringKey, locale: string): string {
  const exact = colorStrings[locale];
  if (exact) {
    return exact[key];
  }

  const language = locale.split("-")[0];
  const match = Object.keys(colorStrings).find((l) => l.split("-")[0] === language);
  if (match) {
    return colorStrings[match][key];
  }

  return colorStrings[DEFAULT_LOCALE][key];
}

/**
 * Mirrors LocalizedStringFormatter.format for the plain `{variable}` messages
 * used by color names (colorName / transparentColorName). Substitutes each
 * `{name}` token with the matching variable's string value.
 */
export function formatColorMessage(
  key: ColorStringKey,
  locale: string,
  variables: Record<string, string>
): string {
  const message = getColorStringForLocale(key, locale);
  return message.replace(/\{(\w+)\}/g, (_, name) =>
    variables[name] !== undefined ? variables[name] : ""
  );
}
