// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/actionbar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/actionbar")({
  head: () =>
    seo({
      title: "ActionBar props",
      description:
        "The 17 props declared for ActionBar in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/actionbar",
    }),
  component: () => <ApiReference page={page} />,
});
