// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/actionbutton.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/actionbutton")({
  head: () =>
    seo({
      title: "ActionButton props",
      description:
        "Every prop ActionButton accepts in @proyecto-viviana/ui — 39 documented from the package's own types.",
      path: "/docs/components/actionbutton",
    }),
  component: () => <ApiReference page={page} />,
});
