// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/actiongroup.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/actiongroup")({
  head: () =>
    seo({
      title: "ActionGroup props",
      description:
        "The 15 props declared for ActionGroup in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/actiongroup",
    }),
  component: () => <ApiReference page={page} />,
});
