// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/actionmenu.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/actionmenu")({
  head: () =>
    seo({
      title: "ActionMenu props",
      description:
        "The 50 props declared for ActionMenu in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/actionmenu",
    }),
  component: () => <ApiReference page={page} />,
});
