// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/actiongroup.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/actiongroup")({
  head: () =>
    seo({
      title: "ActionGroup props",
      description:
        "Every prop ActionGroup accepts in @proyecto-viviana/ui — 15 documented from the package's own types.",
      path: "/docs/components/actiongroup",
    }),
  component: () => <ApiReference page={page} />,
});
