// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/alertdialog.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/alertdialog")({
  head: () =>
    seo({
      title: "AlertDialog props",
      description:
        "Every prop AlertDialog accepts in @proyecto-viviana/ui — 20 documented from the package's own types.",
      path: "/docs/components/alertdialog",
    }),
  component: () => <ApiReference page={page} />,
});
