// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/avatar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/avatar")({
  head: () =>
    seo({
      title: "Avatar props",
      description:
        "The 12 props declared for Avatar in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/avatar",
    }),
  component: () => <ApiReference page={page} />,
});
