// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/badge.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/badge")({
  head: () =>
    seo({
      title: "Badge props",
      description:
        "Every prop Badge accepts in @proyecto-viviana/ui — 12 documented from the package's own types.",
      path: "/docs/components/badge",
    }),
  component: () => <ApiReference page={page} />,
});
