// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/breadcrumbs.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/breadcrumbs")({
  head: () =>
    seo({
      title: "Breadcrumbs props",
      description:
        "The 18 props declared for Breadcrumbs in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/breadcrumbs",
    }),
  component: () => <ApiReference page={page} />,
});
