// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/button.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/button")({
  head: () =>
    seo({
      title: "Button props",
      description:
        "Every prop Button accepts in @proyecto-viviana/ui — 40 documented from the package's own types.",
      path: "/docs/components/button",
    }),
  component: () => <ApiReference page={page} />,
});
