// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/calendar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/calendar")({
  head: () =>
    seo({
      title: "Calendar props",
      description:
        "Every prop Calendar accepts in @proyecto-viviana/ui — 33 documented from the package's own types.",
      path: "/docs/components/calendar",
    }),
  component: () => <ApiReference page={page} />,
});
