// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/card.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/card")({
  head: () =>
    seo({
      title: "Card props",
      description:
        "Every prop Card accepts in @proyecto-viviana/ui — 27 documented from the package's own types.",
      path: "/docs/components/card",
    }),
  component: () => <ApiReference page={page} />,
});
