// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/card.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/card")({
  head: () =>
    seo({
      title: "Card props",
      description:
        "The 29 props declared for Card in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/card",
    }),
  component: () => <ApiReference page={page} />,
});
