// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/cardview.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/cardview")({
  head: () =>
    seo({
      title: "CardView props",
      description:
        "Every prop CardView accepts in @proyecto-viviana/ui — 39 documented from the package's own types.",
      path: "/docs/components/cardview",
    }),
  component: () => <ApiReference page={page} />,
});
