// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/cardview.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/cardview")({
  head: () =>
    seo({
      title: "CardView props",
      description:
        "The 40 props declared for CardView in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/cardview",
    }),
  component: () => <ApiReference page={page} />,
});
