// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/checkbox.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/checkbox")({
  head: () =>
    seo({
      title: "Checkbox props",
      description:
        "The 43 props declared for Checkbox in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/checkbox",
    }),
  component: () => <ApiReference page={page} />,
});
