// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/colorwheel.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/colorwheel")({
  head: () =>
    seo({
      title: "ColorWheel props",
      description:
        "The 22 props declared for ColorWheel in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/colorwheel",
    }),
  component: () => <ApiReference page={page} />,
});
