// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/colorfield.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/colorfield")({
  head: () =>
    seo({
      title: "ColorField props",
      description:
        "Every prop ColorField accepts in @proyecto-viviana/ui — 36 documented from the package's own types.",
      path: "/docs/components/colorfield",
    }),
  component: () => <ApiReference page={page} />,
});
