// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/colorswatchpicker.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/colorswatchpicker")({
  head: () =>
    seo({
      title: "ColorSwatchPicker props",
      description:
        "The 23 props declared for ColorSwatchPicker in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/colorswatchpicker",
    }),
  component: () => <ApiReference page={page} />,
});
