// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/coloreditor.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/coloreditor")({
  head: () =>
    seo({
      title: "ColorEditor props",
      description:
        "The 9 props declared for ColorEditor in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/coloreditor",
    }),
  component: () => <ApiReference page={page} />,
});
