// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/colorarea.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/colorarea")({
  head: () =>
    seo({
      title: "ColorArea props",
      description:
        "Every prop ColorArea accepts in @proyecto-viviana/ui — 20 documented from the package's own types.",
      path: "/docs/components/colorarea",
    }),
  component: () => <ApiReference page={page} />,
});
