// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/colorslider.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/colorslider")({
  head: () =>
    seo({
      title: "ColorSlider props",
      description:
        "Every prop ColorSlider accepts in @proyecto-viviana/ui — 25 documented from the package's own types.",
      path: "/docs/components/colorslider",
    }),
  component: () => <ApiReference page={page} />,
});
