// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/combobox.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/combobox")({
  head: () =>
    seo({
      title: "ComboBox props",
      description:
        "The 123 props declared for ComboBox in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/combobox",
    }),
  component: () => <ApiReference page={page} />,
});
