// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/contextualhelp.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/contextualhelp")({
  head: () =>
    seo({
      title: "ContextualHelp props",
      description:
        "Every prop ContextualHelp accepts in @proyecto-viviana/ui — 71 documented from the package's own types.",
      path: "/docs/components/contextualhelp",
    }),
  component: () => <ApiReference page={page} />,
});
