// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/daterangepicker.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/daterangepicker")({
  head: () =>
    seo({
      title: "DateRangePicker props",
      description:
        "Every prop DateRangePicker accepts in @proyecto-viviana/ui — 50 documented from the package's own types.",
      path: "/docs/components/daterangepicker",
    }),
  component: () => <ApiReference page={page} />,
});
