// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/datepicker.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/datepicker")({
  head: () =>
    seo({
      title: "DatePicker props",
      description:
        "The 53 props declared for DatePicker in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/datepicker",
    }),
  component: () => <ApiReference page={page} />,
});
