// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/disclosure.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/disclosure")({
  head: () =>
    seo({
      title: "Disclosure props",
      description:
        "Every prop Disclosure accepts in @proyecto-viviana/ui — 71 documented from the package's own types.",
      path: "/docs/components/disclosure",
    }),
  component: () => <ApiReference page={page} />,
});
