// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/disclosure.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/disclosure")({
  head: () =>
    seo({
      title: "Disclosure props",
      description:
        "The 17 props declared for Disclosure in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/disclosure",
    }),
  component: () => <ApiReference page={page} />,
});
