// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/divider.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/divider")({
  head: () =>
    seo({
      title: "Divider props",
      description:
        "Every prop Divider accepts in @proyecto-viviana/ui — 13 documented from the package's own types.",
      path: "/docs/components/divider",
    }),
  component: () => <ApiReference page={page} />,
});
