// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/dropzone.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/dropzone")({
  head: () =>
    seo({
      title: "DropZone props",
      description:
        "The 16 props declared for DropZone in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/dropzone",
    }),
  component: () => <ApiReference page={page} />,
});
