// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/filetrigger.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/filetrigger")({
  head: () =>
    seo({
      title: "FileTrigger props",
      description:
        "Every prop FileTrigger accepts in @proyecto-viviana/ui — 7 documented from the package's own types.",
      path: "/docs/components/filetrigger",
    }),
  component: () => <ApiReference page={page} />,
});
