// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/form.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/form")({
  head: () =>
    seo({
      title: "Form props",
      description:
        "Every prop Form accepts in @proyecto-viviana/ui — 25 documented from the package's own types.",
      path: "/docs/components/form",
    }),
  component: () => <ApiReference page={page} />,
});
