// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/gridlist.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/gridlist")({
  head: () =>
    seo({
      title: "ListView props",
      description:
        "The 70 props declared for ListView in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/gridlist",
    }),
  component: () => <ApiReference page={page} />,
});
