// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/hudframe.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/hudframe")({
  head: () =>
    seo({
      title: "HudFrame props",
      description:
        "Every prop HudFrame accepts in @proyecto-viviana/ui — 9 documented from the package's own types.",
      path: "/docs/components/hudframe",
    }),
  component: () => <ApiReference page={page} />,
});
