// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/hudframe.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/hudframe")({
  head: () =>
    seo({
      title: "HudFrame props",
      description:
        "The 9 props declared for HudFrame in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/hudframe",
    }),
  component: () => <ApiReference page={page} />,
});
