// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/illustratedmessage.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/illustratedmessage")({
  head: () =>
    seo({
      title: "IllustratedMessage props",
      description:
        "The 13 props declared for IllustratedMessage in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/illustratedmessage",
    }),
  component: () => <ApiReference page={page} />,
});
