// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/image.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/image")({
  head: () =>
    seo({
      title: "Image props",
      description:
        "The 21 props declared for Image in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/image",
    }),
  component: () => <ApiReference page={page} />,
});
