// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/link.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/link")({
  head: () =>
    seo({
      title: "Link props",
      description:
        "Every prop Link accepts in @proyecto-viviana/ui — 34 documented from the package's own types.",
      path: "/docs/components/link",
    }),
  component: () => <ApiReference page={page} />,
});
