// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/linkbutton.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/linkbutton")({
  head: () =>
    seo({
      title: "LinkButton props",
      description:
        "The 38 props declared for LinkButton in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/linkbutton",
    }),
  component: () => <ApiReference page={page} />,
});
