// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/listbox.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/listbox")({
  head: () =>
    seo({
      title: "ListBox props",
      description:
        "Every prop ListBox accepts in @proyecto-viviana/ui — 72 documented from the package's own types.",
      path: "/docs/components/listbox",
    }),
  component: () => <ApiReference page={page} />,
});
