// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/menu.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/menu")({
  head: () =>
    seo({
      title: "Menu props",
      description:
        "The 152 props declared for Menu in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/menu",
    }),
  component: () => <ApiReference page={page} />,
});
