// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/meter.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/meter")({
  head: () =>
    seo({
      title: "Meter props",
      description:
        "Every prop Meter accepts in @proyecto-viviana/ui — 21 documented from the package's own types.",
      path: "/docs/components/meter",
    }),
  component: () => <ApiReference page={page} />,
});
