// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/notificationbadge.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/notificationbadge")({
  head: () =>
    seo({
      title: "NotificationBadge props",
      description:
        "Every prop NotificationBadge accepts in @proyecto-viviana/ui — 12 documented from the package's own types.",
      path: "/docs/components/notificationbadge",
    }),
  component: () => <ApiReference page={page} />,
});
