// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/numberfield.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/numberfield")({
  head: () =>
    seo({
      title: "NumberField props",
      description:
        "The 46 props declared for NumberField in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/numberfield",
    }),
  component: () => <ApiReference page={page} />,
});
