// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/picker.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/picker")({
  head: () =>
    seo({
      title: "Picker props",
      description:
        "The 58 props declared for Picker in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/picker",
    }),
  component: () => <ApiReference page={page} />,
});
