// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/popover.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/popover")({
  head: () =>
    seo({
      title: "Popover props",
      description:
        "The 49 props declared for Popover in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/popover",
    }),
  component: () => <ApiReference page={page} />,
});
