// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/productcard.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/productcard")({
  head: () =>
    seo({
      title: "ProductCard props",
      description:
        "Every prop ProductCard accepts in @proyecto-viviana/ui — 19 documented from the package's own types.",
      path: "/docs/components/productcard",
    }),
  component: () => <ApiReference page={page} />,
});
