// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/progress.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/progress")({
  head: () =>
    seo({
      title: "ProgressCircle props",
      description:
        "The 17 props declared for ProgressCircle in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/progress",
    }),
  component: () => <ApiReference page={page} />,
});
