// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/progress.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/progress")({
  head: () =>
    seo({
      title: "ProgressCircle props",
      description:
        "Every prop ProgressCircle accepts in @proyecto-viviana/ui — 17 documented from the package's own types.",
      path: "/docs/components/progress",
    }),
  component: () => <ApiReference page={page} />,
});
