// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/progress-bar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/progress-bar")({
  head: () =>
    seo({
      title: "ProgressBar props",
      description:
        "Every prop ProgressBar accepts in @proyecto-viviana/ui — 21 documented from the package's own types.",
      path: "/docs/components/progress-bar",
    }),
  component: () => <ApiReference page={page} />,
});
