// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/radio.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/radio")({
  head: () =>
    seo({
      title: "Radio props",
      description:
        "The 71 props declared for Radio in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/radio",
    }),
  component: () => <ApiReference page={page} />,
});
