// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/rangeslider.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/rangeslider")({
  head: () =>
    seo({
      title: "RangeSlider props",
      description:
        "Every prop RangeSlider accepts in @proyecto-viviana/ui — 32 documented from the package's own types.",
      path: "/docs/components/rangeslider",
    }),
  component: () => <ApiReference page={page} />,
});
