// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/searchfield.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/searchfield")({
  head: () =>
    seo({
      title: "SearchField props",
      description:
        "The 66 props declared for SearchField in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/searchfield",
    }),
  component: () => <ApiReference page={page} />,
});
