// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/segmentedcontrol.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/segmentedcontrol")({
  head: () =>
    seo({
      title: "SegmentedControl props",
      description:
        "Every prop SegmentedControl accepts in @proyecto-viviana/ui — 55 documented from the package's own types.",
      path: "/docs/components/segmentedcontrol",
    }),
  component: () => <ApiReference page={page} />,
});
