// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/selectboxgroup.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/selectboxgroup")({
  head: () =>
    seo({
      title: "SelectBoxGroup props",
      description:
        "Every prop SelectBoxGroup accepts in @proyecto-viviana/ui — 69 documented from the package's own types.",
      path: "/docs/components/selectboxgroup",
    }),
  component: () => <ApiReference page={page} />,
});
