// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/select.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/select")({
  head: () =>
    seo({
      title: "Select props",
      description:
        "The 80 props declared for Select in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/select",
    }),
  component: () => <ApiReference page={page} />,
});
