// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/separator.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/separator")({
  head: () =>
    seo({
      title: "Separator props",
      description:
        "Every prop Separator accepts in @proyecto-viviana/ui — 12 documented from the package's own types.",
      path: "/docs/components/separator",
    }),
  component: () => <ApiReference page={page} />,
});
