// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/separator.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/separator")({
  head: () =>
    seo({
      title: "Separator props",
      description:
        "The 12 props declared for Separator in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/separator",
    }),
  component: () => <ApiReference page={page} />,
});
