// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/skeleton.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/skeleton")({
  head: () =>
    seo({
      title: "Skeleton props",
      description:
        "The 3 props declared for Skeleton in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/skeleton",
    }),
  component: () => <ApiReference page={page} />,
});
