// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/skeleton.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/skeleton")({
  head: () =>
    seo({
      title: "Skeleton props",
      description:
        "Every prop Skeleton accepts in @proyecto-viviana/ui — 3 documented from the package's own types.",
      path: "/docs/components/skeleton",
    }),
  component: () => <ApiReference page={page} />,
});
