// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/slider.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/slider")({
  head: () =>
    seo({
      title: "Slider props",
      description:
        "The 35 props declared for Slider in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/slider",
    }),
  component: () => <ApiReference page={page} />,
});
