// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/steplist.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/steplist")({
  head: () =>
    seo({
      title: "StepList props",
      description:
        "The 19 props declared for StepList in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/steplist",
    }),
  component: () => <ApiReference page={page} />,
});
