// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/table.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/table")({
  head: () =>
    seo({
      title: "Table props",
      description:
        "Every prop Table accepts in @proyecto-viviana/ui — 258 documented from the package's own types.",
      path: "/docs/components/table",
    }),
  component: () => <ApiReference page={page} />,
});
