// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/tabs.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/tabs")({
  head: () =>
    seo({
      title: "Tabs props",
      description:
        "The 23 props declared for Tabs in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/tabs",
    }),
  component: () => <ApiReference page={page} />,
});
