// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/tag-group.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/tag-group")({
  head: () =>
    seo({
      title: "TagGroup props",
      description:
        "The 34 props declared for TagGroup in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/tag-group",
    }),
  component: () => <ApiReference page={page} />,
});
