// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/text.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/text")({
  head: () =>
    seo({
      title: "Text props",
      description:
        "The 14 props declared for Text in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/text",
    }),
  component: () => <ApiReference page={page} />,
});
