// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/textfield.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/textfield")({
  head: () =>
    seo({
      title: "TextField props",
      description:
        "The 121 props declared for TextField in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/textfield",
    }),
  component: () => <ApiReference page={page} />,
});
