// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/text.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/text")({
  head: () =>
    seo({
      title: "Text props",
      description:
        "Every prop Text accepts in @proyecto-viviana/ui — 85 documented from the package's own types.",
      path: "/docs/components/text",
    }),
  component: () => <ApiReference page={page} />,
});
