// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/toast.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/toast")({
  head: () =>
    seo({
      title: "Toast props",
      description:
        "Every prop Toast accepts in @proyecto-viviana/ui — 25 documented from the package's own types.",
      path: "/docs/components/toast",
    }),
  component: () => <ApiReference page={page} />,
});
