// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/togglebutton.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/togglebutton")({
  head: () =>
    seo({
      title: "ToggleButton props",
      description:
        "The 33 props declared for ToggleButton in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/togglebutton",
    }),
  component: () => <ApiReference page={page} />,
});
