// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/toolbar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/toolbar")({
  head: () =>
    seo({
      title: "Toolbar props",
      description:
        "Every prop Toolbar accepts in @proyecto-viviana/ui — 8 documented from the package's own types.",
      path: "/docs/components/toolbar",
    }),
  component: () => <ApiReference page={page} />,
});
