// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/tooltip.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/tooltip")({
  head: () =>
    seo({
      title: "Tooltip props",
      description:
        "Every prop Tooltip accepts in @proyecto-viviana/ui — 42 documented from the package's own types.",
      path: "/docs/components/tooltip",
    }),
  component: () => <ApiReference page={page} />,
});
