// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/toolbar.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/toolbar")({
  head: () =>
    seo({
      title: "Toolbar props",
      description:
        "The 7 props declared for Toolbar in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/toolbar",
    }),
  component: () => <ApiReference page={page} />,
});
