// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/tree.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/tree")({
  head: () =>
    seo({
      title: "Tree props",
      description:
        "Every prop Tree accepts in @proyecto-viviana/ui — 145 documented from the package's own types.",
      path: "/docs/components/tree",
    }),
  component: () => <ApiReference page={page} />,
});
