// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/usercard.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/usercard")({
  head: () =>
    seo({
      title: "UserCard props",
      description:
        "The 20 props declared for UserCard in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/usercard",
    }),
  component: () => <ApiReference page={page} />,
});
