// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/view.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/view")({
  head: () =>
    seo({
      title: "SceneBackdrop props",
      description:
        "The 8 props declared for SceneBackdrop in @proyecto-viviana/ui and the packages under it — inherited DOM attributes are not listed.",
      path: "/docs/components/view",
    }),
  component: () => <ApiReference page={page} />,
});
