// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/view.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/view")({
  head: () =>
    seo({
      title: "SceneBackdrop props",
      description:
        "Every prop SceneBackdrop accepts in @proyecto-viviana/ui — 8 documented from the package's own types.",
      path: "/docs/components/view",
    }),
  component: () => <ApiReference page={page} />,
});
