// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/well.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/well")({
  head: () =>
    seo({
      title: "Well props",
      description:
        "The 3 props declared for Well in @proyecto-viviana/ui and the packages under it — props inherited from outside them are not listed.",
      path: "/docs/components/well",
    }),
  component: () => <ApiReference page={page} />,
});
