// Generated by `vp run api:extract`. Do not edit; change the package's types instead.
import { createFileRoute } from "@tanstack/solid-router";
import { ApiReference } from "@/components/docs";
import page from "@/data/api-reference/pages/well.json";
import { seo } from "@/seo";

export const Route = createFileRoute("/docs/components/well")({
  head: () =>
    seo({
      title: "Well props",
      description:
        "Every prop Well accepts in @proyecto-viviana/ui — 1 documented from the package's own types.",
      path: "/docs/components/well",
    }),
  component: () => <ApiReference page={page} />,
});
