/**
 * Every docs route file on disk must be present in the committed routeTree.
 *
 * `routeTree.gen.ts` is generated by the build and committed, so it goes stale
 * the moment someone adds a page without rebuilding — the file exists, the page
 * 404s, and nothing else notices. Two docs trees now feed it: the hand-authored
 * solid-spectrum tree and the generated `/docs` reference, whose 82 route files
 * are written by `vp run api:extract`.
 */
import { readdir, readFile } from "node:fs/promises";

const trees = [
  {
    basePath: "/solid-spectrum/docs",
    dir: "apps/web/src/routes/solid-spectrum/docs/components",
    segment: "components",
  },
  {
    basePath: "/solid-spectrum/docs",
    dir: "apps/web/src/routes/solid-spectrum/docs/hooks",
    segment: "hooks",
  },
  { basePath: "/docs", dir: "apps/web/src/routes/docs/components", segment: "components" },
];

const routeTreeFile = "apps/web/src/routeTree.gen.ts";

async function listRouteSlugs(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".tsx"))
    .map((entry) => entry.name.replace(".tsx", ""))
    .sort();
}

const expectedPaths: string[] = [];
for (const tree of trees) {
  const slugs = await listRouteSlugs(tree.dir);
  expectedPaths.push(...slugs.map((slug) => `${tree.basePath}/${tree.segment}/${slug}`));
}

const routeTree = await readFile(routeTreeFile, "utf8");
const routePaths = new Set(
  Array.from(routeTree.matchAll(/['"]([^'"]+)['"]/g), (match) => match[1]),
);
const missingPaths = expectedPaths.filter((path) => !routePaths.has(path));

if (missingPaths.length > 0) {
  console.error("Docs routeTree is missing discovered route files:");
  for (const path of missingPaths) {
    console.error(`- ${path}`);
  }
  console.error("Run the router generator/build step so routeTree.gen.ts is up to date.");
  process.exit(1);
}

console.log(`OK: docs routeTree covers ${expectedPaths.length} docs routes.`);
