// Turns a generated theme (dark + light token maps) into the exact CSS a
// consumer pastes to re-skin @proyecto-viviana/ui, plus a one-line how-to.

import { type TokenMap } from "./themeBase";

export const THEME_HOWTO =
  'Import "@proyecto-viviana/ui/theme.css" in your global stylesheet, then paste the block below after it. These rules override the --color-* design tokens the components read, so the whole library adopts your theme. The light block only lists tokens that differ from your dark theme, matching how /ui ships its scheme override.';

function block(selector: string, tokens: TokenMap): string {
  const lines = Object.entries(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${lines}\n}`;
}

export interface ThemeCssInput {
  dark: TokenMap;
  light: TokenMap;
}

/**
 * Full dark map under `:root` (so it fully owns the dark scheme regardless of the
 * library's own defaults) + a light block listing only tokens that differ from
 * the generated dark map (light overrides dark, mirroring the source contract).
 */
export function buildThemeCss({ dark, light }: ThemeCssInput): string {
  const lightOverrides: TokenMap = {};
  for (const k of Object.keys(light)) {
    if (light[k] !== dark[k]) lightOverrides[k] = light[k];
  }

  return [
    "/* Viviana theme — generated by the Theme Studio (proyecto-viviana). */",
    `/* ${THEME_HOWTO} */`,
    "",
    block(":root", dark),
    "",
    block('[data-color-scheme="light"]', lightOverrides),
    "",
  ].join("\n");
}
